apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component.service: postgres-pv-claim
  name:  postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}