apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    component.service: web-claim0
  name: web-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: csi-hostpath-sc      
status: {}