apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
  # namespace: decider-ns
spec:
  type: NodePort
  selector:
    app: decider-web
  ports:
    - name: "web-5000"
      port: 5000
      targetPort: 5000
 

